{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ajio.fullname" . }}-secret
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret.data }}
  {{ $k }}: "{{ $v }}"
  {{- end }}
{{- end }}
